# Generated by Django 3.2.16 on 2023-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_bookmodel_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('phn', models.IntegerField()),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='contactmodel',
        ),
    ]
