# Generated by Django 3.2.16 on 2023-01-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20230106_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('bookprice', models.IntegerField()),
                ('bookdes', models.CharField(max_length=50)),
                ('bookimage', models.FileField(upload_to='bookapp/static/cart')),
            ],
        ),
    ]
