# Generated by Django 3.2.16 on 2023-01-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_addcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='bookdes',
        ),
    ]
